spring.application.name=nivelar

# 1. BANCO DE DADOS (Confirme se a senha Sasuke256 é a mesma do servidor Kodar)
spring.datasource.url=jdbc:postgresql://localhost:5432/nivelar
spring.datasource.username=postgres
spring.datasource.password=Sasuke256

# 2. JPA / HIBERNATE (Segurança em primeiro lugar)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# 3. SERVIDOR E CAMINHO OFICIAL
server.port=8082
server.servlet.context-path=/api

# 4. CONFIGURAÇÃO PARA NGINX / HTTPS (Essencial!)
server.forward-headers-strategy=native

# 5. DIRETÓRIOS DE UPLOAD (Garante que as pastas existem no Linux)
nivelar.upload-dir.profile-pics=/opt/nivelar/uploads/profile-pics
nivelar.upload-dir.registros=/opt/nivelar/uploads/registros

# Defina uma chave longa e nunca mude ela
jwt.secret=KodarSoftwares_Realizza_Controle_ChaveSecreta_2026_Segura

# 6. LOGS (Nível de produção)
logging.level.root=INFO
logging.level.org.springframework.web=INFO

# 7. MULTIPART (Mantido para fotos pesadas)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB